sonar.projectKey=HMS_Sprint4_Frontend
sonar.projectName=HMS_Sprint4_Frontend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
sonar.coverage.exclusions = **
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login = sqp_5d41e24c70531fb25bd5c8cde49535dfe35f1cfb


