name: Deploy HMS Frontend

on:
  push:
    branches:
      - feature/visagan_sprint_5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2 Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_VISAGAN_HOST }}
          username: ${{ secrets.EC2_VISAGAN_USER }}
          key: ${{ secrets.EC2_VISAGAN_SSH }}
          script: |
            set -e

            cd ~/hms_project/HMS-Frontend

            git update-ref -d refs/remotes/origin/feature/visagan_sprint_5 || true
            git fetch origin feature/visagan_sprint_5
            git reset --hard FETCH_HEAD

            npm install
            npm run build

            sudo mkdir -p /var/www/hms-frontend
            sudo rm -rf /var/www/hms-frontend/*

            if [ -d "dist/HMS-Frontend/browser" ]; then
              sudo cp -r dist/HMS-Frontend/browser/* /var/www/hms-frontend/
            elif [ -d "dist/hms-frontend/browser" ]; then
              sudo cp -r dist/hms-frontend/browser/* /var/www/hms-frontend/
            elif [ -d "dist/HMS-Frontend" ]; then
              sudo cp -r dist/HMS-Frontend/* /var/www/hms-frontend/
            elif [ -d "dist/hms-frontend" ]; then
              sudo cp -r dist/hms-frontend/* /var/www/hms-frontend/
            else
              echo "Build folder not found"
              ls -R dist
              exit 1
            fi

            sudo systemctl restart nginx
